### ISSUE TITLE
Editer fichier .gitignore

### ISSUE THREAD

**Issue by zmEpfc** [dyl25/caviste#6]
Il faudrait éditer nos fichier .gitignore présents à la racine de nos projets netbeans respectifs afin de ne plus envoyer le dossier nbProject sur le serveur distant. 
Pour ce faire, il faut ajouter cette ligne dans le fichier .gitignore: 

/nbproject/*

Sinon, chaque fois que l'on clone ou pull le projet,  on télécharge aussi le dossier nbProject qui est présent sur le serveur github.

**Comment by dyl25** [comment]
Fichier gitignore modifié pour la partie avec pdo (branche AvantIntegration)
